apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  ttlSecondsAfterFinished: 1 
  template:
    spec:
      containers:
      - name: migrate
        image: onething/pod-migrate
        #image: nginx:stable-alpine
        command: ["/bin/sh", "-c","\"/copy.sh\""]
        #command: ["/bin/sh", "-c","\"/bin/sleep 10000\""]
        imagePullPolicy: Never
        env:
        - name: NAMESPACE
          value: default 
        - name: POD
          value: mai-0 
        - name: DESNODE
          value: c32010s8
        - name: RootPath
          value: /data
        volumeMounts:
        - name: root
          mountPath: /data
      volumes:
      - name: root
        hostPath:
          path: /
      restartPolicy: Never
      nodeName: c32010s8
      serviceAccountName: migrate-pods-sa
      automountServiceAccountToken: true
  backoffLimit: 0

